# Generated by Django 4.2.16 on 2025-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant'),
        ('cms', '0005_expertindexpage_outro_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tenantid',
            field=models.ManyToManyField(help_text='Choose the tenants for which this answer is applicable', to='tenants.tenant', verbose_name="list of tenant id's"),
        ),
    ]
