# Generated by Django 4.2.16 on 2025-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_expertindexpage_outro_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentURL',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('urlroot', models.URLField(max_length=255, null=True, verbose_name='urlroot')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='description')),
                ('environmenturl', models.ManyToManyField(to='cms.environmenturl', verbose_name="list of environment URL's")),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='tenantid',
            field=models.ManyToManyField(to='cms.tenant', verbose_name="list of tenant id's"),
        ),
    ]
