# Generated by Django 4.2.16 on 2025-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_android_chrome_icon_tenant_apple_touch_icon_and_more"),
        ("cms", "0007_homepage_tenantid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="tenantid",
            field=models.ManyToManyField(
                help_text="Choose the tenants for which this homepage is applicable",
                to="tenants.tenant",
                verbose_name="list of tenant id's",
            ),
        ),
    ]
