# Generated by Django 4.2.28 on 2026-04-04 16:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("cms", "0008_carbonemissioncategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="KidsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Korte tekst onder de titel",
                        max_length=255,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introductietekst voor de kids pagina"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kids page",
                "verbose_name_plural": "Kids pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
