# Generated by Django 6.0.3 on 2026-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_carbonemissioncategory"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="siteid",
            field=models.ManyToManyField(
                help_text="Choose the sites for which this answer is applicable",
                to="wagtailcore.site",
                verbose_name="list of site id's",
            ),
        ),
    ]
