# Generated by Django 6.0.3 on 2026-04-30 09:38

from django.db import migrations, models
from wagtail.models import Site
from wagtail_helpdesk.cms.models import Answer

def fillDefaultSiteInAnswer(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    khsite = Site.objects.filter(site_name="KlimaatHelpdesk").first() 

    #Answer = apps.get_model("wagtail_helpdesk.cms.models", "Answer")
    for answer in Answer.objects.all():
        answer.siteid.set([khsite.id]) 
        answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_answer_siteid"),
    ]

    operations = [
        migrations.RunPython(fillDefaultSiteInAnswer),
    ]
