# Generated by Django 4.2.28 on 2026-04-04 18:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("cms", "0009_kidspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="KidsEventPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Korte tekst onder de titel",
                        max_length=255,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introductietekst voor deze kids event pagina",
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True,
                        help_text="Datum waarop het event plaatsvindt",
                        null=True,
                    ),
                ),
                (
                    "event_location",
                    models.CharField(
                        blank=True, help_text="Locatie van het event", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Kids event page",
                "verbose_name_plural": "Kids event pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="kidspage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Introductietekst voor de kids hoofdpagina"
            ),
        ),
    ]
