# Generated by Django 4.2.28 on 2026-04-05 16:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("cms", "0010_kidseventpage_alter_kidspage_intro"),
    ]

    operations = [
        migrations.CreateModel(
            name="KidsAnswerPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Korte tekst onder de titel",
                        max_length=255,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introductietekst voor het kids antwoord"
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Het antwoord in kindvriendelijke taal"
                    ),
                ),
                (
                    "card_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Afbeelding van het originele vraagkaartje",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kids answer page",
                "verbose_name_plural": "Kids answer pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="kidseventpage",
            name="event_date",
            field=models.DateField(
                blank=True, help_text="Datum van het evenement", null=True
            ),
        ),
        migrations.AlterField(
            model_name="kidseventpage",
            name="event_location",
            field=models.CharField(
                blank=True, help_text="Bijvoorbeeld Tivoli Utrecht", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="KidsQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("child_name", models.CharField(blank=True, max_length=255)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("question_text", models.CharField(max_length=500)),
                (
                    "answer_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Koppel een kids antwoordpagina aan deze vraag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.kidsanswerpage",
                    ),
                ),
                (
                    "card_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kids_questions",
                        to="cms.kidseventpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kids question",
                "verbose_name_plural": "Kids questions",
            },
        ),
        migrations.CreateModel(
            name="KidsDrawing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("child_name", models.CharField(blank=True, max_length=255)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "drawing_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kids_drawings",
                        to="cms.kidseventpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kids drawing",
                "verbose_name_plural": "Kids drawings",
            },
        ),
    ]
