# Generated by Django 6.0.3 on 2026-06-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_answer_setsiteid"),
        ("cms", "0011_kidsanswerpage_alter_kidseventpage_event_date_and_more"),
    ]

    operations = []
