# Generated by Django 6.0.3 on 2026-06-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0012_merge_20260612_1648"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="siteid",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose the sites for which this answer is applicable",
                to="wagtailcore.site",
                verbose_name="list of site id's",
            ),
        ),
    ]
