# Generated by Django 4.2.16 on 2025-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentURL',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('urlroot', models.URLField(max_length=255, null=True, verbose_name='urlroot')),
            ],
        ),
    ]
