# Generated by Django 4.2.16 on 2025-07-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='description')),
                ('environmenturl', models.ManyToManyField(to='tenants.environmenturl', verbose_name="list of environment URL's")),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['id'],
            },
        ),
    ]
