# Generated by Django 4.2.16 on 2025-07-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('tenants', '0002_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='android_chrome_icon',
            field=models.ForeignKey(blank=True, help_text='This is the png icon used for android devices for this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='apple_touch_icon',
            field=models.ForeignKey(blank=True, help_text='This is the png icon used for apple devices for this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='This is the favicon used for display the tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='scss_file',
            field=models.ForeignKey(blank=True, help_text='This is the scss file for this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
