# Generated by Django 6.0.3 on 2026-04-30 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "css_file_name",
                    models.CharField(
                        default="main.css", max_length=50, verbose_name="name"
                    ),
                ),
                (
                    "sitename",
                    models.CharField(max_length=50, null=True, verbose_name="sitename"),
                ),
                (
                    "android_chrome_icon",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the png icon used for android devices for this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "apple_touch_icon",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the png icon used for apple devices for this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the favicon used for display this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the logo used for display this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logofooter",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the logo used in the footer for display this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
