# Generated by Django 6.0.3 on 2026-05-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo_on_black",
            field=models.ForeignKey(
                blank=True,
                help_text="This is the logo used for this site on black background ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
