# Generated by Django 6.0.3 on 2026-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0002_sitesettings_logo_on_black"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="css_file_name",
            field=models.CharField(
                default="mainKH.css", max_length=50, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="sitename",
            field=models.CharField(
                default="KlimaatHelpdesk",
                max_length=50,
                null=True,
                verbose_name="sitename",
            ),
        ),
    ]
